### ISSUE TITLE
Trojan:Win32/Wacatac.B!ml

### ISSUE THREAD

**Issue by Lalika96** [G1ft3dC0d3/MsfMania#9]
Windows 10 Defender detection Trojan:Win32/Wacatac.B!ml

**Comment by lepotekil** [comment]
Hi, you are using public version of MsfMania.
It detected since April.

**Comment by Liikala96** [comment]
Hi don't recognize the pro version? How much would it cost?

**Comment by lepotekil** [comment]
Search about pro version in the README and contact me via mail.
